package gui;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import database.*;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author ACER
 */
public class FrmPhuongTrinh extends javax.swing.JFrame {

    /**
     * Creates new form FrmPhuongTrinh
     */
    MangLuuTruDuLieu LichSu =new MangLuuTruDuLieu();
    UICaSio Mt=null;
    History ls =null;
    void loadmanhinh(){
                txt_x3.setEditable(false);
                txt_x2.setEditable(false);
                Lbx3.setForeground(new Color(0, 0, 0, 0));
                Lbx2.setForeground(new Color(0, 0, 0, 0));
    }
    public FrmPhuongTrinh() {
        initComponents();
        loadmanhinh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Cbn_Bac = new javax.swing.JComboBox<>();
        Lbx3 = new javax.swing.JLabel();
        txt_x2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_x3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Lbx2 = new javax.swing.JLabel();
        Lbx0 = new javax.swing.JLabel();
        txt_x1 = new javax.swing.JTextField();
        Lbx1 = new javax.swing.JLabel();
        txt_x0 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn_TimX = new javax.swing.JButton();
        txt_KetQua = new javax.swing.JTextField();
        btn_exit = new javax.swing.JButton();
        btn_his = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tìm Phương Trình Chứa X");

        Cbn_Bac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bậc 1", "Bậc 2", "Bậc 3" }));
        Cbn_Bac.setToolTipText("");
        Cbn_Bac.setLightWeightPopupEnabled(false);
        Cbn_Bac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cbn_BacActionPerformed(evt);
            }
        });

        Lbx3.setText("ax³ =");

        txt_x2.setAutoscrolls(false);

        Lbx2.setText("bx²=");
        Lbx2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Lbx0.setText("dx   =");

        Lbx1.setText("cx   =");

        txt_x0.setAutoscrolls(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cbn_Bac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(Lbx3)))
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Lbx1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_x3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Lbx0)
                                        .addComponent(Lbx2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txt_x1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_x2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_x0, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Cbn_Bac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbx3)
                    .addComponent(txt_x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Lbx2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbx0)
                    .addComponent(txt_x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbx1)
                    .addComponent(txt_x0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btn_TimX.setText("Tìm X");
        btn_TimX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimXActionPerformed(evt);
            }
        });

        txt_KetQua.setEditable(false);
        txt_KetQua.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btn_exit.setText("Trở về");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_his.setText("History");
        btn_his.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_KetQua)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btn_TimX)
                .addGap(11, 11, 11)
                .addComponent(btn_his)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_exit)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(txt_KetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_TimX)
                    .addComponent(btn_exit)
                    .addComponent(btn_his))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TimXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimXActionPerformed
        int choice = Cbn_Bac.getSelectedIndex();
        String kq="";
        TinhPhuongTrinhX timx =new TinhPhuongTrinhX(choice);
        long startTime = System.currentTimeMillis();// Lấy thời gian bắt đầu
        if(choice ==2)
        {
        double a = Double.parseDouble(txt_x3.getText());
        double b = Double.parseDouble(txt_x2.getText());
        double c = Double.parseDouble(txt_x1.getText());
        double d = Double.parseDouble(txt_x0.getText());
        kq=timx.TimX(a, b, c, d);
        }else if(choice ==1){
            double a = Double.parseDouble(txt_x2.getText());
            double b = Double.parseDouble(txt_x1.getText());
            double c = Double.parseDouble(txt_x0.getText());
            kq=timx.TimX(a, b, c, 0);
        }else if(choice ==0){
            double a = Double.parseDouble(txt_x1.getText());
            double b = Double.parseDouble(txt_x0.getText());
            kq=timx.TimX(a, b, 0, 0);
        }
        long endTime = System.currentTimeMillis(); // Lấy thời gian kết thúc
        double elapsedTime = (endTime - startTime) / 1000.0; // Chuyển thành giây
        txt_KetQua.setText(kq);
        LuuTruDuLieu tamthoi =new LuuTruDuLieu(kq, elapsedTime);
        LichSu.them(tamthoi);
    }//GEN-LAST:event_btn_TimXActionPerformed

    private void Cbn_BacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cbn_BacActionPerformed
        int choice = Cbn_Bac.getSelectedIndex();
                
                if(choice==0)
                {
                txt_x3.setEditable(false);
                txt_x2.setEditable(false);
                Lbx3.setForeground(new Color(0, 0, 0, 0));
                Lbx2.setForeground(new Color(0, 0, 0, 0));
                }
                if(choice==1){
                txt_x3.setEditable(false);
                txt_x2.setEditable(true);
                Lbx3.setForeground(new Color(0, 0, 0, 0));
                Lbx2.setForeground(Color.BLACK);
                }
                if(choice==2){
                txt_x3.setEditable(true);
                txt_x2.setEditable(true);
                Lbx3.setForeground(Color.BLACK);
                Lbx2.setForeground(Color.BLACK);
                }           
    }//GEN-LAST:event_Cbn_BacActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        if(Mt==null)
        {
            Mt=new UICaSio();
            Mt.setVisible(true);
        }else {Mt.toFront();}
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_hisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hisActionPerformed
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("His.txt"))) {
            for (LuuTruDuLieu it :LichSu.getMang()) {
                writer.write(it.tostring());
                writer.newLine(); // Xuống dòng sau mỗi phần tử
            }
            System.out.println("Ghi ArrayList vào file thành công!");
        } catch (IOException e) {
            System.out.println("Lỗi khi ghi file: " + e.getMessage());
        }
        if(ls==null)
        {
            ls=new History();
            ls.setVisible(true);
        }else {ls.toFront();ls.ViewTable();}
    }//GEN-LAST:event_btn_hisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPhuongTrinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPhuongTrinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPhuongTrinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPhuongTrinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPhuongTrinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cbn_Bac;
    private javax.swing.JLabel Lbx0;
    private javax.swing.JLabel Lbx1;
    private javax.swing.JLabel Lbx2;
    private javax.swing.JLabel Lbx3;
    private javax.swing.JButton btn_TimX;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_his;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_KetQua;
    private javax.swing.JTextField txt_x0;
    private javax.swing.JTextField txt_x1;
    private javax.swing.JTextField txt_x2;
    private javax.swing.JTextField txt_x3;
    // End of variables declaration//GEN-END:variables
}
