/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import database.*;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
/**
 *
 * @author ACER
 */
public class UICaSio extends javax.swing.JFrame {

    /**
     * Creates new form UICaSio
     */
    XuLyDuLieu dauvao = new XuLyDuLieu();
    String temp="";
    MangLuuTruDuLieu LichSu =new MangLuuTruDuLieu();
    public UICaSio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txt_Display = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Btn_1 = new javax.swing.JButton();
        Btn_2 = new javax.swing.JButton();
        Btn_3 = new javax.swing.JButton();
        Btn_Cong = new javax.swing.JButton();
        Btn_4 = new javax.swing.JButton();
        Btn_5 = new javax.swing.JButton();
        Btn_6 = new javax.swing.JButton();
        Btn_Tru = new javax.swing.JButton();
        Btn_7 = new javax.swing.JButton();
        Btn_8 = new javax.swing.JButton();
        Btn_9 = new javax.swing.JButton();
        Btn_Nhan = new javax.swing.JButton();
        Btn_0 = new javax.swing.JButton();
        BtnPoint = new javax.swing.JButton();
        Btn_DauBang = new javax.swing.JButton();
        Btn_Chia = new javax.swing.JButton();
        Btn_AC = new javax.swing.JButton();
        Btn_DEL = new javax.swing.JButton();
        Btn_His = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_Display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Display.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_Display))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txt_Display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        txt_Display.getAccessibleContext().setAccessibleName("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Casio");

        jPanel2.setLayout(new java.awt.GridLayout(4, 5));

        Btn_1.setText("1");
        Btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_1ActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_1);

        Btn_2.setText("2");
        Btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_2ActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_2);

        Btn_3.setText("3");
        Btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_2ActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_3);

        Btn_Cong.setText("+");
        Btn_Cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CongActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Cong);

        Btn_4.setText("4");
        Btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_2ActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_4);

        Btn_5.setText("5");
        Btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_2ActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_5);

        Btn_6.setText("6");
        Btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_6ActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_6);

        Btn_Tru.setText("-");
        Btn_Tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CongActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Tru);

        Btn_7.setText("7");
        Btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_2ActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_7);

        Btn_8.setText("8");
        Btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_2ActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_8);

        Btn_9.setText("9");
        Btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_2ActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_9);

        Btn_Nhan.setText("*");
        Btn_Nhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NhanActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Nhan);

        Btn_0.setText("0");
        Btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_2ActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_0);

        BtnPoint.setText(".");
        BtnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_6ActionPerformed(evt);
            }
        });
        jPanel2.add(BtnPoint);

        Btn_DauBang.setText("=");
        Btn_DauBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DauBangActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_DauBang);

        Btn_Chia.setText("/");
        Btn_Chia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CongActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Chia);

        Btn_AC.setText("AC");
        Btn_AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ACActionPerformed(evt);
            }
        });

        Btn_DEL.setText("DEL");
        Btn_DEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DELActionPerformed(evt);
            }
        });

        Btn_His.setText("His");
        Btn_His.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_HisActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Btn_AC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_DEL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_His)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Btn_AC)
                    .addComponent(Btn_DEL)
                    .addComponent(Btn_His))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_1ActionPerformed
        String cmd =evt.getActionCommand();
        temp =temp+cmd;
        txt_Display.setText(temp);
    }//GEN-LAST:event_Btn_1ActionPerformed

    private void Btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_6ActionPerformed
        String cmd =evt.getActionCommand();
        temp =temp+cmd;
        txt_Display.setText(temp);
    }//GEN-LAST:event_Btn_6ActionPerformed

    private void Btn_NhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NhanActionPerformed
        String cmd =evt.getActionCommand();
        temp  =temp+" "+cmd+" ";
        txt_Display.setText(temp);
    }//GEN-LAST:event_Btn_NhanActionPerformed

    private void Btn_CongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CongActionPerformed
        String cmd =evt.getActionCommand();
        temp  =temp+" "+cmd+" ";
        txt_Display.setText(temp);
    }//GEN-LAST:event_Btn_CongActionPerformed

    private void Btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_2ActionPerformed
        String cmd =evt.getActionCommand();
        temp =temp+cmd;
        txt_Display.setText(temp);
    }//GEN-LAST:event_Btn_2ActionPerformed

    private void Btn_DauBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DauBangActionPerformed
       LuuTruDuLieu tamthoi=new LuuTruDuLieu();
       temp=temp.trim().replaceAll("\\s+", " ");
       String[] mang =temp.split(" ");
       for(String it :mang)
           dauvao.themDuLieu(it);
       long startTime = System.currentTimeMillis();// Lấy thời gian bắt đầu
       dauvao.xulytaoketqua();
       long endTime = System.currentTimeMillis(); // Lấy thời gian kết thúc
       double elapsedTime = (endTime - startTime) / 1000.0; // Chuyển thành giây
       tamthoi.setThoigianthuchien(elapsedTime);
       tamthoi.setDuLieuPhepTinh(dauvao.HienThiDuLieu());
       LichSu.them(tamthoi);
       txt_Display.setText(dauvao.HienThiDuLieu());
       System.out.println(dauvao.HienThiDuLieu());
       temp="";
       dauvao.rsDuLieu();
    }//GEN-LAST:event_Btn_DauBangActionPerformed

    private void Btn_ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ACActionPerformed
       temp="";
       txt_Display.setText(temp);
       dauvao.rsDuLieu();
    }//GEN-LAST:event_Btn_ACActionPerformed

    private void Btn_DELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DELActionPerformed
       if(!temp.equals(""))
       {
       if(temp.substring(temp.length()-1).equals(" "))
          temp = temp.substring(0, temp.length() - 3);
       else 
          temp = temp.substring(0, temp.length() - 1);
        txt_Display.setText(temp);
       }
    }//GEN-LAST:event_Btn_DELActionPerformed

    private void Btn_HisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_HisActionPerformed
       try (BufferedWriter writer = new BufferedWriter(new FileWriter("His.txt"))) {
            for (LuuTruDuLieu it :LichSu.getMang()) {
                writer.write(it.tostring());
                writer.newLine(); // Xuống dòng sau mỗi phần tử
            }
            System.out.println("Ghi ArrayList vào file thành công!");
        } catch (IOException e) {
            System.out.println("Lỗi khi ghi file: " + e.getMessage());
        }
       History ls =new History();
       ls.setVisible(true);
    }//GEN-LAST:event_Btn_HisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UICaSio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UICaSio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UICaSio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UICaSio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UICaSio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPoint;
    private javax.swing.JButton Btn_0;
    private javax.swing.JButton Btn_1;
    private javax.swing.JButton Btn_2;
    private javax.swing.JButton Btn_3;
    private javax.swing.JButton Btn_4;
    private javax.swing.JButton Btn_5;
    private javax.swing.JButton Btn_6;
    private javax.swing.JButton Btn_7;
    private javax.swing.JButton Btn_8;
    private javax.swing.JButton Btn_9;
    private javax.swing.JButton Btn_AC;
    private javax.swing.JButton Btn_Chia;
    private javax.swing.JButton Btn_Cong;
    private javax.swing.JButton Btn_DEL;
    private javax.swing.JButton Btn_DauBang;
    private javax.swing.JButton Btn_His;
    private javax.swing.JButton Btn_Nhan;
    private javax.swing.JButton Btn_Tru;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_Display;
    // End of variables declaration//GEN-END:variables
}
